{"cells":[{"cell_type":"code","execution_count":23,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"SG0c2_O1J8UJ","outputId":"e3c62549-ff21-4140-c64a-7c8d88d5a273","executionInfo":{"status":"ok","timestamp":1729490950229,"user_tz":-420,"elapsed":6632,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive', force_remount=True)"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"NkIwO501KIhe","outputId":"35656c46-c74e-4459-b5a7-2152ca786a61"},"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-cc0a6896f88f>\", line 4, in <cell line: 4>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/Disertasi-Ahmad-Rofiqul/002.Experiment_SWI_16052024/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-cc0a6896f88f>\", line 4, in <cell line: 4>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/Disertasi-Ahmad-Rofiqul/002.Experiment_SWI_16052024/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-24-cc0a6896f88f>\", line 4, in <cell line: 4>\n","    get_ipython().run_line_magic('cd', '/content/drive/MyDrive/Colab Notebooks/Disertasi-Ahmad-Rofiqul/002.Experiment_SWI_16052024/')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"<decorator-gen-85>\", line 2, in cd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in <lambda>\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 342, in cd\n","    oldcwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Path to google drive folder\n","# %cd /content/drive/MyDrive/Colab Notebooks/Disertasi-Ahmad-Rofiqul/002. Laporan-eksperimen\n","\n","%cd /content/drive/MyDrive/Colab Notebooks/Disertasi-Ahmad-Rofiqul/002.Experiment_SWI_16052024/"]},{"cell_type":"code","execution_count":24,"metadata":{"id":"E3maRHbiKSMZ","executionInfo":{"status":"ok","timestamp":1729490950229,"user_tz":-420,"elapsed":4,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[],"source":["import numpy as np\n","import pandas as pd\n","from scipy import stats\n","from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score\n","from sklearn.ensemble import IsolationForest, RandomForestClassifier\n","from sklearn.cluster import DBSCAN\n","from sklearn.decomposition import PCA\n","from sklearn.preprocessing import StandardScaler\n","from sklearn.impute import SimpleImputer\n","from sklearn.metrics import classification_report\n","from xgboost import XGBRegressor, DMatrix, cv\n","from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error\n","from sklearn.svm import OneClassSVM\n","from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, f1_score, classification_report, ConfusionMatrixDisplay, confusion_matrix\n","from sklearn.linear_model import LogisticRegression\n","from sklearn.ensemble import StackingClassifier\n","from sklearn.base import BaseEstimator, ClassifierMixin\n","import xgboost as xgb"]},{"cell_type":"code","source":["!ls"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"hSf0yMJ6-dxS","executionInfo":{"status":"ok","timestamp":1729490951223,"user_tz":-420,"elapsed":998,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"6b152897-0f1c-4d6f-d19e-d4d53b248214"},"execution_count":25,"outputs":[{"output_type":"stream","name":"stdout","text":["shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected\n","ls: cannot open directory '.': Transport endpoint is not connected\n"]}]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"cB3eaRnqKU1A","outputId":"12498835-4022-4d15-870b-919a3d4ad238"},"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-26-8dfe4547f597>\", line 3, in <cell line: 3>\n","    data = pd.read_csv(file_path)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n","    return _read(filepath_or_buffer, kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 620, in _read\n","    parser = TextFileReader(filepath_or_buffer, **kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1620, in __init__\n","    self._engine = self._make_engine(f, self.engine)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1880, in _make_engine\n","    self.handles = get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 873, in get_handle\n","    handle = open(\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/agriculture_dataset.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-26-8dfe4547f597>\", line 3, in <cell line: 3>\n","    data = pd.read_csv(file_path)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n","    return _read(filepath_or_buffer, kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 620, in _read\n","    parser = TextFileReader(filepath_or_buffer, **kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1620, in __init__\n","    self._engine = self._make_engine(f, self.engine)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1880, in _make_engine\n","    self.handles = get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 873, in get_handle\n","    handle = open(\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/agriculture_dataset.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-26-8dfe4547f597>\", line 3, in <cell line: 3>\n","    data = pd.read_csv(file_path)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1026, in read_csv\n","    return _read(filepath_or_buffer, kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 620, in _read\n","    parser = TextFileReader(filepath_or_buffer, **kwds)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1620, in __init__\n","    self._engine = self._make_engine(f, self.engine)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py\", line 1880, in _make_engine\n","    self.handles = get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 873, in get_handle\n","    handle = open(\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/agriculture_dataset.csv'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Load the dataset\n","file_path = '01.Dataset-Rofiqul/agriculture_dataset.csv'\n","data = pd.read_csv(file_path)\n","\n","# Display the first few rows of the dataset for review\n","data.head(),data.info(),data.describe()"]},{"cell_type":"markdown","metadata":{"id":"cvC5kqWgyvO3"},"source":["## Detect Nilai NaN"]},{"cell_type":"code","execution_count":26,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":773},"id":"gDng0fbFyr3m","outputId":"9470fcfd-97e0-4c70-f643-934e95329020","executionInfo":{"status":"ok","timestamp":1729490951223,"user_tz":-420,"elapsed":20,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[{"output_type":"execute_result","data":{"text/plain":["Date           0\n","Year           0\n","Experiment     0\n","DataUse        0\n","Replication    0\n","Month          0\n","Vegetation     0\n","VegType        0\n","N2O            0\n","N_rate         0\n","PP2            0\n","PP7            0\n","AirT           0\n","DAF_TD         0\n","DAF_SD         0\n","WFPS25cm       0\n","NH4            0\n","NO3            0\n","Clay           0\n","Sand           0\n","SOM            0\n","GroundTruth    0\n","dtype: int64"],"text/html":["<div>\n","<style scoped>\n","    .dataframe tbody tr th:only-of-type {\n","        vertical-align: middle;\n","    }\n","\n","    .dataframe tbody tr th {\n","        vertical-align: top;\n","    }\n","\n","    .dataframe thead th {\n","        text-align: right;\n","    }\n","</style>\n","<table border=\"1\" class=\"dataframe\">\n","  <thead>\n","    <tr style=\"text-align: right;\">\n","      <th></th>\n","      <th>0</th>\n","    </tr>\n","  </thead>\n","  <tbody>\n","    <tr>\n","      <th>Date</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Year</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Experiment</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DataUse</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Replication</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Month</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Vegetation</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>VegType</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N2O</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N_rate</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP2</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP7</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>AirT</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_TD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_SD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>WFPS25cm</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NH4</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NO3</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Clay</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Sand</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>SOM</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>GroundTruth</th>\n","      <td>0</td>\n","    </tr>\n","  </tbody>\n","</table>\n","</div><br><label><b>dtype:</b> int64</label>"]},"metadata":{},"execution_count":26}],"source":["\n","missing_values_count = data.isna().sum()\n","missing_values_count"]},{"cell_type":"markdown","metadata":{"id":"yzcM1q5Ay_KD"},"source":["## Impute NaN or missing value with Mean"]},{"cell_type":"code","execution_count":27,"metadata":{"colab":{"base_uri":"https://localhost:8080/","height":773},"id":"cT6ViegGy-Xx","outputId":"4f21c99f-330d-41c6-89c9-a4a07f275989","executionInfo":{"status":"ok","timestamp":1729490951223,"user_tz":-420,"elapsed":19,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[{"output_type":"execute_result","data":{"text/plain":["Date           0\n","Year           0\n","Experiment     0\n","DataUse        0\n","Replication    0\n","Month          0\n","Vegetation     0\n","VegType        0\n","N2O            0\n","N_rate         0\n","PP2            0\n","PP7            0\n","AirT           0\n","DAF_TD         0\n","DAF_SD         0\n","WFPS25cm       0\n","NH4            0\n","NO3            0\n","Clay           0\n","Sand           0\n","SOM            0\n","GroundTruth    0\n","dtype: int64"],"text/html":["<div>\n","<style scoped>\n","    .dataframe tbody tr th:only-of-type {\n","        vertical-align: middle;\n","    }\n","\n","    .dataframe tbody tr th {\n","        vertical-align: top;\n","    }\n","\n","    .dataframe thead th {\n","        text-align: right;\n","    }\n","</style>\n","<table border=\"1\" class=\"dataframe\">\n","  <thead>\n","    <tr style=\"text-align: right;\">\n","      <th></th>\n","      <th>0</th>\n","    </tr>\n","  </thead>\n","  <tbody>\n","    <tr>\n","      <th>Date</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Year</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Experiment</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DataUse</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Replication</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Month</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Vegetation</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>VegType</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N2O</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N_rate</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP2</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP7</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>AirT</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_TD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_SD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>WFPS25cm</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NH4</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NO3</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Clay</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Sand</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>SOM</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>GroundTruth</th>\n","      <td>0</td>\n","    </tr>\n","  </tbody>\n","</table>\n","</div><br><label><b>dtype:</b> int64</label>"]},"metadata":{},"execution_count":27}],"source":["# List of columns to impute missing values with the mean\n","columns_to_impute = ['N2O', 'N_rate', 'AirT', 'WFPS25cm', 'NO3', 'NH4', 'Clay', 'Sand']\n","\n","# Loop through each column and fill NaN with the mean of the respective column\n","for column in columns_to_impute:\n","    data.loc[:, column] = data[column].fillna(data[column].mean())\n","\n","\n","# Verify that there are no missing values left\n","missing_values_after_imputation = data.isna().sum()\n","missing_values_after_imputation\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"me_lLqPzzh7s","outputId":"934dc12a-9e45-49f7-eba2-5a05e1c39673"},"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-28-27e4f02067dc>\", line 3, in <cell line: 3>\n","    data.to_csv(output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-28-27e4f02067dc>\", line 3, in <cell line: 3>\n","    data.to_csv(output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-28-27e4f02067dc>\", line 3, in <cell line: 3>\n","    data.to_csv(output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Save the cleaned dataset to a new CSV file\n","output_file_path = '01.Dataset-Rofiqul/BeforeRemoveOutliers/001.input_NaN_mean_agriculture_dataset.csv'\n","data.to_csv(output_file_path, index=False)\n","\n","output_file_path"]},{"cell_type":"markdown","metadata":{"id":"20-tcycQ8NOh"},"source":["## Detect NaN Value"]},{"cell_type":"code","execution_count":28,"metadata":{"id":"gn8lvAlk8NOh","outputId":"b100b026-428d-4fe6-c4b4-bf2585341c46","colab":{"base_uri":"https://localhost:8080/","height":773},"executionInfo":{"status":"ok","timestamp":1729490951223,"user_tz":-420,"elapsed":15,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[{"output_type":"execute_result","data":{"text/plain":["Date           0\n","Year           0\n","Experiment     0\n","DataUse        0\n","Replication    0\n","Month          0\n","Vegetation     0\n","VegType        0\n","N2O            0\n","N_rate         0\n","PP2            0\n","PP7            0\n","AirT           0\n","DAF_TD         0\n","DAF_SD         0\n","WFPS25cm       0\n","NH4            0\n","NO3            0\n","Clay           0\n","Sand           0\n","SOM            0\n","GroundTruth    0\n","dtype: int64"],"text/html":["<div>\n","<style scoped>\n","    .dataframe tbody tr th:only-of-type {\n","        vertical-align: middle;\n","    }\n","\n","    .dataframe tbody tr th {\n","        vertical-align: top;\n","    }\n","\n","    .dataframe thead th {\n","        text-align: right;\n","    }\n","</style>\n","<table border=\"1\" class=\"dataframe\">\n","  <thead>\n","    <tr style=\"text-align: right;\">\n","      <th></th>\n","      <th>0</th>\n","    </tr>\n","  </thead>\n","  <tbody>\n","    <tr>\n","      <th>Date</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Year</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Experiment</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DataUse</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Replication</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Month</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Vegetation</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>VegType</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N2O</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>N_rate</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP2</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>PP7</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>AirT</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_TD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>DAF_SD</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>WFPS25cm</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NH4</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>NO3</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Clay</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>Sand</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>SOM</th>\n","      <td>0</td>\n","    </tr>\n","    <tr>\n","      <th>GroundTruth</th>\n","      <td>0</td>\n","    </tr>\n","  </tbody>\n","</table>\n","</div><br><label><b>dtype:</b> int64</label>"]},"metadata":{},"execution_count":28}],"source":["missing_values_count = data.isna().sum()\n","missing_values_count"]},{"cell_type":"code","execution_count":29,"metadata":{"id":"s00x6-hm8NOh","outputId":"a1128101-2fc6-49fb-cd26-e5bef98d196a","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1729490951223,"user_tz":-420,"elapsed":14,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}}},"outputs":[{"output_type":"stream","name":"stdout","text":["<class 'pandas.core.frame.DataFrame'>\n","RangeIndex: 2246 entries, 0 to 2245\n","Data columns (total 22 columns):\n"," #   Column       Non-Null Count  Dtype  \n","---  ------       --------------  -----  \n"," 0   Date         2246 non-null   object \n"," 1   Year         2246 non-null   float64\n"," 2   Experiment   2246 non-null   object \n"," 3   DataUse      2246 non-null   object \n"," 4   Replication  2246 non-null   object \n"," 5   Month        2246 non-null   object \n"," 6   Vegetation   2246 non-null   object \n"," 7   VegType      2246 non-null   object \n"," 8   N2O          2246 non-null   float64\n"," 9   N_rate       2246 non-null   float64\n"," 10  PP2          2246 non-null   float64\n"," 11  PP7          2246 non-null   float64\n"," 12  AirT         2246 non-null   float64\n"," 13  DAF_TD       2246 non-null   float64\n"," 14  DAF_SD       2246 non-null   float64\n"," 15  WFPS25cm     2246 non-null   float64\n"," 16  NH4          2246 non-null   float64\n"," 17  NO3          2246 non-null   float64\n"," 18  Clay         2246 non-null   float64\n"," 19  Sand         2246 non-null   float64\n"," 20  SOM          2246 non-null   float64\n"," 21  GroundTruth  2246 non-null   int64  \n","dtypes: float64(14), int64(1), object(7)\n","memory usage: 386.2+ KB\n"]}],"source":["data.info()"]},{"cell_type":"markdown","metadata":{"id":"Uy1jmKkI0QNZ"},"source":["## StandartScaler"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"cEc-iZpu0OrQ","outputId":"6247c26b-9f6b-4908-aafd-e701af1b5781"},"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-720d7ae0b8a6>\", line 10, in <cell line: 10>\n","    data.to_csv(scaled_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-720d7ae0b8a6>\", line 10, in <cell line: 10>\n","    data.to_csv(scaled_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-720d7ae0b8a6>\", line 10, in <cell line: 10>\n","    data.to_csv(scaled_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Initialize the StandardScaler\n","scaler = StandardScaler()\n","\n","# Apply StandardScaler to the numerical columns\n","numerical_columns = data.select_dtypes(include=['float64', 'int64']).columns\n","data[numerical_columns] = scaler.fit_transform(data[numerical_columns])\n","\n","# Save the scaled dataset to a new CSV file\n","scaled_output_file_path = '01.Dataset-Rofiqul/BeforeRemoveOutliers/002.standard_scaler_agriculture_dataset.csv'\n","data.to_csv(scaled_output_file_path, index=False)\n","\n","# Display the head of the scaled dataset\n","scaled_data_head = data.head()\n","scaled_data_head, scaled_output_file_path"]},{"cell_type":"markdown","source":["## IQR Detect Outlier for Groundtruth"],"metadata":{"id":"wg0puxu2M_3A"}},{"cell_type":"code","source":["# \"\"\"## IQR Outlier Detection and Groundtruth Creation\"\"\"\n","\n","# # Function to calculate IQR bounds\n","# def iqr_bounds(series):\n","#     Q1 = series.quantile(0.25)\n","#     Q3 = series.quantile(0.75)\n","#     IQR = Q3 - Q1\n","#     lower_bound = Q1 - 1.5 * IQR\n","#     upper_bound = Q3 + 1.5 * IQR\n","#     return lower_bound, upper_bound\n","\n","# # Detect outliers and create summary table\n","# summary_table = []\n","# groundtruth = pd.DataFrame(index=data.index)  # To store outliers\n","\n","# for col in numerical_columns:\n","#     lower_bound_IQR, upper_bound_IQR = iqr_bounds(data[col])\n","\n","#     # Detect outliers\n","#     outliers_IQR = (data[col] < lower_bound_IQR) | (data[col] > upper_bound_IQR)\n","\n","#     # Store the outlier information in the 'groundtruth' dataframe\n","#     groundtruth[col + '_outlier'] = outliers_IQR.astype(int)  # 1 for outlier, 0 for non-outlier\n","\n","#     # Append information to summary table\n","#     summary_table.append({\n","#         'Column': col,\n","#         'Method': 'IQR',\n","#         'Lower Bound': lower_bound_IQR,\n","#         'Upper Bound': upper_bound_IQR,\n","#         'Outlier Count': outliers_IQR.sum()\n","#     })\n","\n","# # Convert the summary table into a DataFrame for review\n","# summary_df = pd.DataFrame(summary_table)\n","# print(\"Outlier Summary IQR:\\n\", summary_df)\n","\n","# # Create the Groundtruth column by checking if there is any outlier in any column\n","# groundtruth['Groundtruth'] = groundtruth.any(axis=1).astype(int)  # 1 if outlier in any column, 0 if not\n","\n","# # Add the groundtruth to the original data (not scaled)\n","# data_with_groundtruth = pd.concat([data, groundtruth['Groundtruth']], axis=1)\n","\n","# # Save the dataset with Groundtruth column\n","# groundtruth_output_file_path = '01.Dataset-Rofiqul/BeforeRemoveOutliers/003.groundtruth_agriculture_dataset.csv'\n","# data_with_groundtruth.to_csv(groundtruth_output_file_path, index=False)\n","\n","# print(\"Groundtruth dataset saved at:\", groundtruth_output_file_path)\n","# # Example outlier detection using IQR (Interquartile Range)\n","# Q1 = data['N2O'].quantile(0.25)\n","# Q3 = data['N2O'].quantile(0.75)\n","# IQR = Q3 - Q1\n","# lower_bound = Q1 - 1.5 * IQR\n","# upper_bound = Q3 + 1.5 * IQR\n","\n","# # Define GroundTruth based on IQR\n","# data['GroundTruth'] = np.where((data['N2O'] < lower_bound) | (data['N2O'] > upper_bound), -1, 1)\n","\n","# # Select features for model input (X) and GroundTruth as the label (y)\n","# X = data[['N2O', 'N_rate', 'AirT', 'WFPS25cm', 'NO3', 'NH4', 'Clay', 'Sand']]  # Selected features\n","# y = data['GroundTruth']  # GroundTruth as the label (-1 for outlier, 1 for inlier)\n","\n","# # Split data into train and test sets\n","# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n","\n","# # Verify the shapes of the training and testing sets\n","# print(\"X_train shape:\", X_train.shape)\n","# print(\"y_train shape:\", y_train.shape)\n","# print(\"X_test shape:\", X_test.shape)\n","# print(\"y_test shape:\", y_test.shape)\n","\n","# # Save the dataset with the GroundTruth column\n","# groundtruth_output_file_path = '01.Dataset-Rofiqul/BeforeRemoveOutliers/003.groundtruth_agriculture_dataset.csv'\n","# data.to_csv(groundtruth_output_file_path, index=False)\n","\n","# print(\"Groundtruth dataset saved at:\", groundtruth_output_file_path)\n","\n","# # Create a summary DataFrame to show counts of inliers and outliers\n","# summary_df = pd.DataFrame({\n","#     'Inliers (1)': [np.sum(data['GroundTruth'] == 1)],\n","#     'Outliers (-1)': [np.sum(data['GroundTruth'] == -1)]\n","# })\n","\n","# # Display the summary of inliers and outliers\n","# print(\"Summary of GroundTruth labels:\")\n","# print(summary_df)\n","# Extract the N2O column\n","N2O_data = data['N2O']\n","\n","# Detect outliers using IQR method\n","Q1 = N2O_data.quantile(0.25)\n","Q3 = N2O_data.quantile(0.75)\n","IQR = Q3 - Q1\n","lower_bound = Q1 - 1.5 * IQR\n","upper_bound = Q3 + 1.5 * IQR\n","\n","# Define GroundTruth based on IQR only for N2O\n","data['GroundTruth'] = np.where((N2O_data < lower_bound) | (N2O_data > upper_bound), -1, 1)\n","\n","# Select features for model input (X) and GroundTruth as the label (y)\n","# X = data[['N_rate', 'AirT', 'WFPS25cm', 'NO3', 'NH4', 'Clay', 'Sand']]  # Use only non-N2O features\n","X = data[['N2O']]  # Use only non-N2O features\n","y = data['GroundTruth']  # GroundTruth as the label (-1 for outlier, 1 for inlier)\n","\n","# Split data into train and test sets\n","X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)\n","\n","# Verify the shapes of the training and testing sets\n","print(\"X_train shape:\", X_train.shape)\n","print(\"y_train shape:\", y_train.shape)\n","print(\"X_test shape:\", X_test.shape)\n","print(\"y_test shape:\", y_test.shape)\n","\n","# Save the dataset with the GroundTruth column\n","groundtruth_output_file_path = '01.Dataset-Rofiqul/BeforeRemoveOutliers/003.groundtruth_agriculture_dataset.csv'\n","data.to_csv(groundtruth_output_file_path, index=False)\n","\n","print(\"Groundtruth dataset saved at:\", groundtruth_output_file_path)\n","\n","# Create a summary DataFrame to show counts of inliers and outliers\n","summary_df = pd.DataFrame({\n","    'Inliers (1)': [np.sum(data['GroundTruth'] == 1)],\n","    'Outliers (-1)': [np.sum(data['GroundTruth'] == -1)]\n","})\n","\n","# Display the summary of inliers and outliers\n","print(\"Summary of GroundTruth labels:\")\n","print(summary_df)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"5lLzCsqmNEN3","outputId":"8f9f298d-4429-41ac-dc3d-7a613001fa7a"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["X_train shape: (1572, 1)\n","y_train shape: (1572,)\n","X_test shape: (674, 1)\n","y_test shape: (674,)\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-4ed824ce874f>\", line 116, in <cell line: 116>\n","    data.to_csv(groundtruth_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-4ed824ce874f>\", line 116, in <cell line: 116>\n","    data.to_csv(groundtruth_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-30-4ed824ce874f>\", line 116, in <cell line: 116>\n","    data.to_csv(groundtruth_output_file_path, index=False)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/util/_decorators.py\", line 333, in wrapper\n","    return func(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py\", line 3967, in to_csv\n","    return DataFrameRenderer(formatter).to_csv(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/format.py\", line 1014, in to_csv\n","    csv_formatter.save()\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/formats/csvs.py\", line 251, in save\n","    with get_handle(\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 749, in get_handle\n","    check_parent_directory(str(handle))\n","  File \"/usr/local/lib/python3.10/dist-packages/pandas/io/common.py\", line 615, in check_parent_directory\n","    if not parent.is_dir():\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1305, in is_dir\n","    return S_ISDIR(self.stat().st_mode)\n","  File \"/usr/lib/python3.10/pathlib.py\", line 1097, in stat\n","    return self._accessor.stat(self, follow_symlinks=follow_symlinks)\n","OSError: [Errno 107] Transport endpoint is not connected: '01.Dataset-Rofiqul/BeforeRemoveOutliers'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]},{"cell_type":"markdown","source":["# Isolation Forest"],"metadata":{"id":"QhkwmYinQO8p"}},{"cell_type":"code","source":["# Train and predict using Isolation Forest\n","iso_forest = IsolationForest(contamination=0.06, random_state=42)\n","\n","\n","iso_forest.fit(X_train)\n","y_pred_if = iso_forest.predict(X_test)\n","\n","# Performance Evaluation for Isolation Forest\n","\n","# Evaluate Isolation Forest using the IQR-based GroundTruth\n","accuracy_if = accuracy_score(y_test, y_pred_if)\n","precision_if = precision_score(y_test, y_pred_if, pos_label=-1)\n","recall_if = recall_score(y_test, y_pred_if, pos_label=-1)\n","f1_if = f1_score(y_test, y_pred_if, pos_label=-1)\n","\n","# Display performance metrics for Isolation Forest\n","print(\"Performance Metrics for Isolation Forest (using GroundTruth from IQR):\")\n","print(f\"Accuracy: {accuracy_if:.2f}\")\n","print(f\"Precision: {precision_if:.2f}\")\n","print(f\"Recall: {recall_if:.2f}\")\n","print(f\"F1-Score: {f1_if:.2f}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"HmlIOVx5QSLQ","executionInfo":{"status":"ok","timestamp":1729490951578,"user_tz":-420,"elapsed":361,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"ccf25cd0-38cd-4d2a-ba0f-03bafd31dda0"},"execution_count":30,"outputs":[{"output_type":"stream","name":"stdout","text":["Performance Metrics for Isolation Forest (using GroundTruth from IQR):\n","Accuracy: 0.94\n","Precision: 0.83\n","Recall: 0.49\n","F1-Score: 0.62\n"]}]},{"cell_type":"markdown","source":["#DBScan"],"metadata":{"id":"n7g1rPwYSzeB"}},{"cell_type":"code","source":["# Train and predict using DBSCAN\n","dbscan = DBSCAN(eps=0.5, min_samples=2)\n","y_pred_db = dbscan.fit_predict(X_test)\n","\n","# Convert DBSCAN predictions to binary (outliers = -1, inliers = 1)\n","y_pred_db_binary = np.where(y_pred_db == -1, -1, 1)\n","\n","# Evaluate DBSCAN (using binary labels)\n","accuracy_db = accuracy_score(y_test, y_pred_db_binary)\n","precision_db = precision_score(y_test, y_pred_db_binary, pos_label=-1)\n","recall_db = recall_score(y_test, y_pred_db_binary, pos_label=-1)\n","f1_db = f1_score(y_test, y_pred_db_binary, pos_label=-1)\n","\n","print(f\"DBSCAN           - Accuracy: {accuracy_db:.2f}, Precision: {precision_db:.2f}, Recall: {recall_db:.2f}, F1-Score: {f1_db:.2f}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"c-MkIGyBS1cQ","executionInfo":{"status":"ok","timestamp":1729490951578,"user_tz":-420,"elapsed":6,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"c0317286-bf7c-477f-9e6b-6bdb69544cb3"},"execution_count":31,"outputs":[{"output_type":"stream","name":"stdout","text":["DBSCAN           - Accuracy: 0.90, Precision: 1.00, Recall: 0.03, F1-Score: 0.06\n"]}]},{"cell_type":"markdown","source":["# One Class SVM"],"metadata":{"id":"Cw5zqKDQTGVf"}},{"cell_type":"code","source":["# Train and predict using One-Class SVM\n","ocsvm = OneClassSVM(nu=0.05, kernel='rbf', gamma='auto')\n","# ocsvm = OneClassSVM(nu=0.5, kernel='linear', gamma=0.01)\n","y_pred_svm = ocsvm.fit_predict(X_test)\n","\n","# Evaluate One-Class SVM\n","accuracy_svm = accuracy_score(y_test, y_pred_svm)\n","precision_svm = precision_score(y_test, y_pred_svm, pos_label=-1)\n","recall_svm = recall_score(y_test, y_pred_svm, pos_label=-1)\n","f1_svm = f1_score(y_test, y_pred_svm, pos_label=-1)\n","\n","print(f\"One-Class SVM    - Accuracy: {accuracy_svm:.2f}, Precision: {precision_svm:.2f}, Recall: {recall_svm:.2f}, F1-Score: {f1_svm:.2f}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"nvyjXCmZTH9x","executionInfo":{"status":"ok","timestamp":1729490951578,"user_tz":-420,"elapsed":5,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"7f5730e5-49a4-4ba7-fb2b-e93430026e6c"},"execution_count":32,"outputs":[{"output_type":"stream","name":"stdout","text":["One-Class SVM    - Accuracy: 0.92, Precision: 0.72, Recall: 0.38, F1-Score: 0.50\n"]}]},{"cell_type":"markdown","source":["# Display Performance for each model"],"metadata":{"id":"7G9X-52NTYb4"}},{"cell_type":"code","source":["# Display performance metrics for each model\n","print(\"Performance Metrics for Individual Models:\")\n","print(f\"Isolation Forest - Accuracy: {accuracy_if:.2f}, Precision: {precision_if:.2f}, Recall: {recall_if:.2f}, F1-Score: {f1_if:.2f}\")\n","print(f\"DBSCAN           - Accuracy: {accuracy_db:.2f}, Precision: {precision_db:.2f}, Recall: {recall_db:.2f}, F1-Score: {f1_db:.2f}\")\n","print(f\"One-Class SVM    - Accuracy: {accuracy_svm:.2f}, Precision: {precision_svm:.2f}, Recall: {recall_svm:.2f}, F1-Score: {f1_svm:.2f}\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"6AHOGmA_TcDP","executionInfo":{"status":"ok","timestamp":1729490951578,"user_tz":-420,"elapsed":4,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"0b0089c7-4b00-4f7a-d9f1-d49fb4d88a02"},"execution_count":33,"outputs":[{"output_type":"stream","name":"stdout","text":["Performance Metrics for Individual Models:\n","Isolation Forest - Accuracy: 0.94, Precision: 0.83, Recall: 0.49, F1-Score: 0.62\n","DBSCAN           - Accuracy: 0.90, Precision: 1.00, Recall: 0.03, F1-Score: 0.06\n","One-Class SVM    - Accuracy: 0.92, Precision: 0.72, Recall: 0.38, F1-Score: 0.50\n"]}]},{"cell_type":"markdown","source":["# Ensemble (Manual)"],"metadata":{"id":"YglqO2sST6aQ"}},{"cell_type":"code","source":["# Combine the predictions using majority voting\n","\n","# Collect predictions from all models\n","predictions = np.vstack([y_pred_if, y_pred_db_binary, y_pred_svm]).T\n","\n","# Majority voting (mode of predictions)\n","y_pred_ensemble_majority = stats.mode(predictions, axis=1)[0].flatten()\n","\n","# Evaluate the majority voting ensemble's performance\n","accuracy_majority = accuracy_score(y_test, y_pred_ensemble_majority)\n","error_rate_majority = 1 - accuracy_majority\n","precision_majority = precision_score(y_test, y_pred_ensemble_majority, pos_label=-1)\n","recall_majority = recall_score(y_test, y_pred_ensemble_majority, pos_label=-1)\n","f1_majority = f1_score(y_test, y_pred_ensemble_majority, pos_label=-1)\n","\n","print(\"\\nPerformance Metrics for Majority Voting Ensemble:\")\n","print(f\"Majority Voting - Accuracy: {accuracy_majority:.2f}, Error Rate: {error_rate_majority:.2f}, Precision: {precision_majority:.2f}, Recall: {recall_majority:.2f}, F1-Score: {f1_majority:.2f}\")\n","\n","# Weighted Voting\n","# Assign weights to the models (you can adjust these based on individual model performance)\n","weights = [0.5, 0.1, 0.4]  # Example: 40% for Isolation Forest, 30% for DBSCAN, 30% for One-Class SVM\n","# weights = [0.3, 0.5, 0.2]  # Example: 40% for Isolation Forest, 30% for DBSCAN, 30% for One-Class SVM\n","\n","# Convert the predictions from (-1, 1) to (0, 1) for easier summing\n","predictions_binary = np.where(predictions == -1, 0, 1)\n","\n","# Perform weighted voting\n","weighted_sum = np.dot(predictions_binary, weights)\n","\n","# Setup threshold\n","threshold = 0.5\n","\n","# Convert weighted sum back to (-1, 1) labels: if sum >= 0.5, predict inlier (1); else outlier (-1)\n","y_pred_ensemble_weighted = np.where(weighted_sum >= threshold, 1, -1)\n","\n","# Evaluate the weighted voting ensemble's performance\n","accuracy_weighted = accuracy_score(y_test, y_pred_ensemble_weighted)\n","error_rate_weighted = 1 - accuracy_weighted\n","precision_weighted = precision_score(y_test, y_pred_ensemble_weighted, pos_label=-1)\n","recall_weighted = recall_score(y_test, y_pred_ensemble_weighted, pos_label=-1)\n","f1_weighted = f1_score(y_test, y_pred_ensemble_weighted, pos_label=-1)\n","\n","print(\"\\nPerformance Metrics for Weighted Voting Ensemble:\")\n","print(f\"Weighted Voting - Accuracy: {accuracy_weighted:.2f}, Error Rate: {error_rate_weighted:.2f}, Precision: {precision_weighted:.2f}, Recall: {recall_weighted:.2f}, F1-Score: {f1_weighted:.2f}\")\n","\n","# Display performance comparison for all models and ensembles\n","accuracy_if = accuracy_score(y_test, y_pred_if)\n","error_rate_if = 1 - accuracy_if\n","accuracy_db = accuracy_score(y_test, y_pred_db_binary)\n","error_rate_db = 1 - accuracy_db\n","accuracy_svm = accuracy_score(y_test, y_pred_svm)\n","error_rate_svm = 1 - accuracy_svm\n","\n","print(\"\\nPerformance Metrics for Individual Models, Majority Voting, and Weighted Voting:\")\n","print(f\"Isolation Forest - Accuracy: {accuracy_if:.2f}, Error Rate: {error_rate_if:.2f}, Precision: {precision_if:.2f}, Recall: {recall_if:.2f}, F1-Score: {f1_if:.2f}\")\n","print(f\"DBSCAN           - Accuracy: {accuracy_db:.2f}, Error Rate: {error_rate_db:.2f}, Precision: {precision_db:.2f}, Recall: {recall_db:.2f}, F1-Score: {f1_db:.2f}\")\n","print(f\"One-Class SVM    - Accuracy: {accuracy_svm:.2f}, Error Rate: {error_rate_svm:.2f}, Precision: {precision_svm:.2f}, Recall: {recall_svm:.2f}, F1-Score: {f1_svm:.2f}\")\n","print(f\"Majority Voting  - Accuracy: {accuracy_majority:.2f}, Error Rate: {error_rate_majority:.2f}, Precision: {precision_majority:.2f}, Recall: {recall_majority:.2f}, F1-Score: {f1_majority:.2f}\")\n","print(f\"Weighted Voting  - Accuracy: {accuracy_weighted:.2f}, Error Rate: {error_rate_weighted:.2f}, Precision: {precision_weighted:.2f}, Recall: {recall_weighted:.2f}, F1-Score: {f1_weighted:.2f}\")\n","\n","# # Check if the models are making diverse predictions\n","# agreement = np.sum(np.all(predictions == predictions[:, [0]], axis=1)) / len(predictions)\n","# print(f\"Percentage of total agreement between all models: {agreement * 100:.2f}%\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"HEHooUIjT8DB","executionInfo":{"status":"ok","timestamp":1729490951578,"user_tz":-420,"elapsed":3,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"b23c5cd4-46e8-4c8c-a103-4796e49effb9"},"execution_count":34,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Performance Metrics for Majority Voting Ensemble:\n","Majority Voting - Accuracy: 0.93, Error Rate: 0.07, Precision: 0.79, Recall: 0.38, F1-Score: 0.51\n","\n","Performance Metrics for Weighted Voting Ensemble:\n","Weighted Voting - Accuracy: 0.93, Error Rate: 0.07, Precision: 0.79, Recall: 0.38, F1-Score: 0.51\n","\n","Performance Metrics for Individual Models, Majority Voting, and Weighted Voting:\n","Isolation Forest - Accuracy: 0.94, Error Rate: 0.06, Precision: 0.83, Recall: 0.49, F1-Score: 0.62\n","DBSCAN           - Accuracy: 0.90, Error Rate: 0.10, Precision: 1.00, Recall: 0.03, F1-Score: 0.06\n","One-Class SVM    - Accuracy: 0.92, Error Rate: 0.08, Precision: 0.72, Recall: 0.38, F1-Score: 0.50\n","Majority Voting  - Accuracy: 0.93, Error Rate: 0.07, Precision: 0.79, Recall: 0.38, F1-Score: 0.51\n","Weighted Voting  - Accuracy: 0.93, Error Rate: 0.07, Precision: 0.79, Recall: 0.38, F1-Score: 0.51\n"]}]},{"cell_type":"markdown","source":["# XGBoost Prediction"],"metadata":{"id":"1V2HNmcRm96i"}},{"cell_type":"code","source":["# # --- Prediksi XGBoost ---\n","\n","# # Fungsi untuk menghitung metrik evaluasi\n","# def evaluate_model(y_true, y_pred):\n","#     mse = mean_squared_error(y_true, y_pred)\n","#     rmse = np.sqrt(mse)\n","#     mae = mean_absolute_error(y_true, y_pred)\n","#     r2 = r2_score(y_true, y_pred)\n","#     return mse, rmse, mae, r2\n","\n","# # --- Gunakan prediksi weighted voting untuk menentukan data inliers ---\n","# inliers_mask_test = y_pred_ensemble_weighted == 1  # Inliers adalah yang diprediksi sebagai 1 di X_test\n","\n","# # Pastikan N2O tidak digunakan sebagai fitur input\n","# X_inliers_test = X_test[inliers_mask_test].drop(columns=['N2O'])  # Hapus kolom N2O dari fitur input\n","# y_inliers_test = X_test[inliers_mask_test]['N2O']  # Target adalah kolom N2O\n","\n","# # --- Split data inliers menjadi training dan testing set untuk model XGBoost ---\n","# X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=0.3, random_state=42)\n","\n","# # --- Inisialisasi dan latih model XGBoost ---\n","# xg_reg = XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,\n","#                       max_depth=5, alpha=10, n_estimators=100)\n","\n","# xg_reg.fit(X_train_inliers, y_train_inliers)\n","\n","# # --- Prediksi N2O pada data testing ---\n","# y_pred_xgb = xg_reg.predict(X_test_inliers)\n","\n","# # --- Evaluasi hasil prediksi ---\n","# mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb)\n","\n","# # Cetak metrik evaluasi regresi\n","# print(\"\\nEvaluation Metrics for XGBoost Regressor on N2O Emissions:\")\n","# print(f\"R-squared (R2): {r2:.2f}\")\n","# print(f\"Mean Absolute Error (MAE): {mae:.2f}\")\n","# print(f\"Mean Squared Error (MSE): {mse:.2f}\")\n","# print(f\"Root Mean Squared Error (RMSE): {rmse:.2f}\")\n","\n","# --- Prediksi XGBoost ---\n","\n","# Fungsi untuk menghitung metrik evaluasi\n","def evaluate_model(y_true, y_pred):\n","    mse = mean_squared_error(y_true, y_pred)\n","    rmse = np.sqrt(mse)\n","    mae = mean_absolute_error(y_true, y_pred)\n","    r2 = r2_score(y_true, y_pred)\n","    return mse, rmse, mae, r2\n","\n","# --- Gunakan prediksi weighted voting untuk menentukan data inliers ---\n","inliers_mask_test = y_pred_ensemble_weighted == 1  # Inliers adalah yang diprediksi sebagai 1 di X_test\n","X_inliers_test = X_test[inliers_mask_test]  # Data yang tidak terdeteksi sebagai outliers di X_test\n","y_inliers_test = y_test[inliers_mask_test]  # Hanya prediksi N2O untuk data inliers di X_test\n","\n","# --- Split data inliers menjadi training dan testing set untuk model XGBoost ---\n","X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=0.3, random_state=42)\n","\n","# --- Inisialisasi dan latih model XGBoost ---\n","xg_reg = XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,\n","                      max_depth=5, alpha=10, n_estimators=100)\n","\n","xg_reg.fit(X_train_inliers, y_train_inliers)\n","\n","# --- Prediksi N2O pada data testing ---\n","y_pred_xgb = xg_reg.predict(X_test_inliers)\n","\n","# --- Evaluasi hasil prediksi ---\n","mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb)\n","\n","# Cetak metrik evaluasi regresi\n","print(\"\\nEvaluation Metrics for XGBoost Regressor on N2O Emissions:\")\n","print(f\"R-squared (R2): {r2:.2f}\")\n","print(f\"Mean Absolute Error (MAE): {mae:.2f}\")\n","print(f\"Mean Squared Error (MSE): {mse:.2f}\")\n","print(f\"Root Mean Squared Error (RMSE): {rmse:.2f}\")\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"aj88-z_rnBt7","executionInfo":{"status":"ok","timestamp":1729490952551,"user_tz":-420,"elapsed":975,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"045d7476-f144-480d-cf7f-28616c4f0191"},"execution_count":35,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Evaluation Metrics for XGBoost Regressor on N2O Emissions:\n","R-squared (R2): 0.89\n","Mean Absolute Error (MAE): 0.05\n","Mean Squared Error (MSE): 0.03\n","Root Mean Squared Error (RMSE): 0.16\n"]}]},{"cell_type":"markdown","source":["# KFold Validation"],"metadata":{"id":"r12XoNVVtRNu"}},{"cell_type":"code","source":["# KFold XGBoost\n","def kfold_xgboost(X_train, y_train):\n","    params = {\n","        'objective': 'reg:squarederror',\n","        'learning_rate': 0.1,\n","        'max_depth': 5,\n","        'alpha': 10,\n","        'colsample_bytree': 0.3\n","    }\n","    dtrain = DMatrix(X_train, label=y_train)\n","\n","    # 5-fold cross-validation menggunakan num_boost_round\n","    cv_results = xgb.cv(dtrain=dtrain, params=params, nfold=5, num_boost_round=100,\n","                        metrics=['rmse', 'mae'], as_pandas=True, seed=42)\n","\n","    return cv_results\n","\n","# Prepare an empty dictionary to store results\n","results = {\n","    \"Test Size\": [],\n","    \"CV MSE\": [],\n","    \"MSE\": [],\n","    \"RMSE\": [],\n","    \"MAE\": [],\n","    \"R2\": []\n","}\n","\n","# Simulasi pengujian dengan berbagai test sizes (20%, 25%, 30%, 35%)\n","test_sizes = [0.2, 0.25, 0.3, 0.35]\n","\n","for test_size in test_sizes:\n","    # Split data into train and test sets\n","    X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=test_size, random_state=42)\n","\n","    # Train the XGBoost model\n","    xg_reg = XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,\n","                          max_depth=5, alpha=10, n_estimators=100)\n","    xg_reg.fit(X_train_inliers, y_train_inliers)\n","\n","    # Predict the test data\n","    y_pred_xgb = xg_reg.predict(X_test_inliers)\n","\n","    # Evaluate predictions\n","    mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb)\n","\n","    # --- KFold Cross-Validation ---\n","    kfold_results = kfold_xgboost(X_train_inliers, y_train_inliers)\n","    mse_cv = kfold_results['test-rmse-mean'].values[-1] ** 2\n","    rmse_cv = np.sqrt(mse_cv)\n","\n","    # Store the results for this test size\n","    results[\"Test Size\"].append(f\"{int(test_size*100)}%\")\n","    results[\"CV MSE\"].append(round(mse_cv, 4))\n","    results[\"MSE\"].append(round(mse, 4))\n","    results[\"RMSE\"].append(round(rmse, 4))\n","    results[\"MAE\"].append(round(mae, 4))\n","    results[\"R2\"].append(round(r2, 4))\n","\n","# Convert results to DataFrame\n","results_df = pd.DataFrame(results)\n","\n","# Display the DataFrame as a text-based table (easily copyable)\n","results_df\n","print(\"\\nPrediction Evaluation with KFold XGBoost\")\n","print(results_df.to_string(index=False))\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"PxIDmx-vtTO1","executionInfo":{"status":"ok","timestamp":1729490953903,"user_tz":-420,"elapsed":1353,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"8dfc1d9d-9e57-4d01-dba9-5516e8bccf94"},"execution_count":36,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Prediction Evaluation with KFold XGBoost\n","Test Size  CV MSE    MSE   RMSE    MAE     R2\n","      20%  0.0114 0.0279 0.1672 0.0569 0.8924\n","      25%  0.0206 0.0305 0.1746 0.0616 0.8803\n","      30%  0.0164 0.0267 0.1634 0.0511 0.8855\n","      35%  0.0229 0.0271 0.1646 0.0574 0.8975\n"]}]},{"cell_type":"markdown","source":["# Standart Cross Validation"],"metadata":{"id":"daGUjdpV27kW"}},{"cell_type":"code","source":["import pandas as pd\n","from tabulate import tabulate\n","\n","# Fungsi untuk Standard Cross-Validation dengan cross_val_score\n","def standard_cross_validation(X_train, y_train):\n","    xg_reg = XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,\n","                          max_depth=5, alpha=10, n_estimators=100)\n","\n","    # 5-fold cross-validation\n","    kfold = KFold(n_splits=5, shuffle=True, random_state=42)\n","\n","    # Mean Squared Error\n","    mse_scores = cross_val_score(xg_reg, X_train, y_train, cv=kfold, scoring='neg_mean_squared_error')\n","    mae_scores = cross_val_score(xg_reg, X_train, y_train, cv=kfold, scoring='neg_mean_absolute_error')\n","    r2_scores = cross_val_score(xg_reg, X_train, y_train, cv=kfold, scoring='r2')\n","\n","    # Take the mean and convert negative MSE and MAE to positive\n","    mse_mean = -np.mean(mse_scores)\n","    rmse_mean = np.sqrt(mse_mean)\n","    mae_mean = -np.mean(mae_scores)\n","    r2_mean = np.mean(r2_scores)\n","\n","    return mse_mean, rmse_mean, mae_mean, r2_mean\n","\n","# Prepare an empty dictionary to store results\n","results_standard_cv = {\n","    \"Test Size\": [],\n","    \"CV MSE\": [],\n","    \"MSE\": [],\n","    \"RMSE\": [],\n","    \"MAE\": [],\n","    \"R²\": []\n","}\n","\n","# Simulasi pengujian dengan berbagai test sizes (20%, 25%, 30%, 35%)\n","test_sizes = [0.2, 0.25, 0.3, 0.35]\n","\n","for test_size in test_sizes:\n","    # Split data into train and test sets\n","    X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=test_size, random_state=42)\n","\n","    # Train the XGBoost model\n","    xg_reg = XGBRegressor(objective='reg:squarederror', colsample_bytree=0.3, learning_rate=0.1,\n","                          max_depth=5, alpha=10, n_estimators=100)\n","    xg_reg.fit(X_train_inliers, y_train_inliers)\n","\n","    # Predict the test data\n","    y_pred_xgb = xg_reg.predict(X_test_inliers)\n","\n","    # Evaluate predictions\n","    mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb)\n","\n","    # --- Standard Cross-Validation ---\n","    mse_cv, rmse_cv, mae_cv, r2_cv = standard_cross_validation(X_train_inliers, y_train_inliers)\n","\n","    # Store the results for this test size\n","    results_standard_cv[\"Test Size\"].append(f\"{int(test_size*100)}%\")\n","    results_standard_cv[\"CV MSE\"].append(round(mse_cv, 4))\n","    results_standard_cv[\"MSE\"].append(round(mse, 4))\n","    results_standard_cv[\"RMSE\"].append(round(rmse, 4))\n","    results_standard_cv[\"MAE\"].append(round(mae, 4))\n","    results_standard_cv[\"R²\"].append(round(r2, 4))\n","\n","# Convert results to DataFrame\n","results_standard_cv_df = pd.DataFrame(results_standard_cv)\n","\n","# Display the DataFrame as a formatted table\n","table_str = tabulate(results_standard_cv_df, headers='keys', tablefmt='grid', showindex=False)\n","print(\"\\nPrediction Evaluation with Standard Cross-Validation\")\n","print(table_str)\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"VwfSl3Di3Alt","executionInfo":{"status":"ok","timestamp":1729490957814,"user_tz":-420,"elapsed":3912,"user":{"displayName":"Ahmad Muslikh","userId":"10473513443774370558"}},"outputId":"39efff14-f373-4aec-fc96-6c35bdb4a309"},"execution_count":37,"outputs":[{"output_type":"stream","name":"stdout","text":["\n","Prediction Evaluation with Standard Cross-Validation\n","+-------------+----------+--------+--------+--------+--------+\n","| Test Size   |   CV MSE |    MSE |   RMSE |    MAE |     R² |\n","+=============+==========+========+========+========+========+\n","| 20%         |   0.0119 | 0.0279 | 0.1672 | 0.0569 | 0.8924 |\n","+-------------+----------+--------+--------+--------+--------+\n","| 25%         |   0.0277 | 0.0305 | 0.1746 | 0.0616 | 0.8803 |\n","+-------------+----------+--------+--------+--------+--------+\n","| 30%         |   0.0187 | 0.0267 | 0.1634 | 0.0511 | 0.8855 |\n","+-------------+----------+--------+--------+--------+--------+\n","| 35%         |   0.0252 | 0.0271 | 0.1646 | 0.0574 | 0.8975 |\n","+-------------+----------+--------+--------+--------+--------+\n"]}]},{"cell_type":"markdown","source":["# GridSearchCV"],"metadata":{"id":"fxvATbVF6sS0"}},{"cell_type":"code","source":["# Set hyperparameters for tuning\n","param_grid = {\n","    'learning_rate': [0.01, 0.05, 0.1],\n","    'max_depth': [3, 5, 7],\n","    'n_estimators': [100, 200],\n","    'subsample': [0.8, 1.0],\n","    'colsample_bytree': [0.6, 0.8]\n","}\n","\n","# Simulasi pengujian dengan berbagai test sizes (20%, 25%, 30%, 35%)\n","test_sizes = [0.2, 0.25, 0.3, 0.35]\n","\n","# Prepare an empty dictionary to store results\n","results = {\n","    \"Test Size\": [],\n","    \"CV MSE\": [],\n","    \"MSE\": [],\n","    \"RMSE\": [],\n","    \"MAE\": [],\n","    \"R²\": []\n","}\n","\n","for test_size in test_sizes:\n","    # Split data into train and test sets\n","    X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=test_size, random_state=42)\n","\n","    # Inisialisasi XGBoost Regressor\n","    xg_reg = XGBRegressor(objective='reg:squarederror')\n","\n","    # GridSearchCV untuk hyperparameter tuning\n","    grid_search = GridSearchCV(estimator=xg_reg, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)\n","    grid_search.fit(X_train_inliers, y_train_inliers)\n","\n","    # Predict with the best model\n","    best_model = grid_search.best_estimator_\n","    y_pred_xgb = best_model.predict(X_test_inliers)\n","\n","    # Evaluasi hasil prediksi\n","    mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb)\n","\n","    # Simpan hasil Cross-Validation MSE (dikonversi dari negatif)\n","    cv_mse = -grid_search.best_score_\n","\n","    # Simpan hasil ke dictionary\n","    results[\"Test Size\"].append(f\"{int(test_size * 100)}%\")\n","    results[\"CV MSE\"].append(round(cv_mse, 4))\n","    results[\"MSE\"].append(round(mse, 4))\n","    results[\"RMSE\"].append(round(rmse, 4))\n","    results[\"MAE\"].append(round(mae, 4))\n","    results[\"R²\"].append(round(r2, 4))\n","\n","# Konversi hasil ke dalam DataFrame\n","results_df = pd.DataFrame(results)\n","\n","# Tampilkan hasil sebagai tabel yang mudah dibaca\n","print(\"\\nPrediction Evaluation with XGBoost GridSearchCV Hyperparameter Tuning\")\n","print(results_df.to_string(index=False))\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"SrW0xxDZ6xqT","outputId":"764368be-fad6-4e4b-9929-71492ee142fb"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/initializers.py:28: UserWarning: Unable to introspect viztracer state: [Errno 107] Transport endpoint is not connected\n","  warnings.warn(f\"Unable to introspect viztracer state: {e}\")\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-0c3b23c4f479>\", line 32, in <cell line: 23>\n","    grid_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1573, in _run_search\n","    evaluate_candidates(ParameterGrid(self.param_grid))\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-0c3b23c4f479>\", line 32, in <cell line: 23>\n","    grid_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1573, in _run_search\n","    evaluate_candidates(ParameterGrid(self.param_grid))\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-0c3b23c4f479>\", line 32, in <cell line: 23>\n","    grid_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1573, in _run_search\n","    evaluate_candidates(ParameterGrid(self.param_grid))\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]},{"cell_type":"markdown","source":["#RandomizedSearchCV"],"metadata":{"id":"ykHZFU9oz9gb"}},{"cell_type":"code","source":["# Import necessary libraries\n","from sklearn.model_selection import RandomizedSearchCV\n","import pandas as pd\n","from tabulate import tabulate\n","\n","# Set hyperparameters for tuning in RandomizedSearchCV\n","param_distributions = {\n","    'learning_rate': [0.01, 0.05, 0.1, 0.2],\n","    'max_depth': [3, 5, 7, 10],\n","    'n_estimators': [50, 100, 200],\n","    'subsample': [0.6, 0.8, 1.0],\n","    'colsample_bytree': [0.6, 0.8, 1.0],\n","    'gamma': [0, 0.1, 0.3, 0.5],\n","    'reg_alpha': [0, 0.01, 0.1],\n","    'reg_lambda': [0.01, 0.1, 1.0]\n","}\n","\n","# Prepare an empty dictionary to store RandomizedSearchCV results\n","results_random_search = {\n","    \"Test Size\": [],\n","    \"CV MSE\": [],\n","    \"MSE\": [],\n","    \"RMSE\": [],\n","    \"MAE\": [],\n","    \"R²\": []\n","}\n","\n","# Simulasi pengujian dengan berbagai test sizes (20%, 25%, 30%, 35%)\n","test_sizes = [0.2, 0.25, 0.3, 0.35]\n","\n","for test_size in test_sizes:\n","    # Split data into train and test sets\n","    X_train_inliers, X_test_inliers, y_train_inliers, y_test_inliers = train_test_split(X_inliers_test, y_inliers_test, test_size=test_size, random_state=42)\n","\n","    # Inisialisasi XGBoost Regressor\n","    xg_reg = XGBRegressor(objective='reg:squarederror')\n","\n","    # RandomizedSearchCV untuk hyperparameter tuning\n","    random_search = RandomizedSearchCV(\n","        estimator=xg_reg,\n","        param_distributions=param_distributions,\n","        n_iter=50,  # Jumlah iterasi, dapat diatur lebih besar atau lebih kecil tergantung kebutuhan\n","        cv=5,  # 5-fold cross-validation\n","        scoring='neg_mean_squared_error',\n","        random_state=42,\n","        n_jobs=-1\n","    )\n","\n","    # Fit RandomizedSearchCV model\n","    random_search.fit(X_train_inliers, y_train_inliers)\n","\n","    # Predict with the best model found by RandomizedSearchCV\n","    best_model_random = random_search.best_estimator_\n","    y_pred_xgb_random = best_model_random.predict(X_test_inliers)\n","\n","    # Evaluasi hasil prediksi\n","    mse, rmse, mae, r2 = evaluate_model(y_test_inliers, y_pred_xgb_random)\n","\n","    # Simpan hasil Cross-Validation MSE (dikonversi dari negatif)\n","    cv_mse = -random_search.best_score_\n","\n","    # Simpan hasil ke dictionary\n","    results_random_search[\"Test Size\"].append(f\"{int(test_size * 100)}%\")\n","    results_random_search[\"CV MSE\"].append(round(cv_mse, 4))\n","    results_random_search[\"MSE\"].append(round(mse, 4))\n","    results_random_search[\"RMSE\"].append(round(rmse, 4))\n","    results_random_search[\"MAE\"].append(round(mae, 4))\n","    results_random_search[\"R²\"].append(round(r2, 4))\n","\n","# Konversi hasil ke dalam DataFrame\n","results_random_search_df = pd.DataFrame(results_random_search)\n","\n","# Tampilkan hasil sebagai tabel yang mudah dibaca\n","print(\"\\nPrediction Evaluation with XGBoost RandomizedSearchCV Hyperparameter Tuning\")\n","print(results_random_search_df.to_string(index=False))\n"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ASLPcRkE0AaH","outputId":"9de559fc-a180-4389-ffb5-5160a9ec2134"},"execution_count":null,"outputs":[{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-a339aeb5a6c6>\", line 50, in <cell line: 31>\n","    random_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1960, in _run_search\n","    evaluate_candidates(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-a339aeb5a6c6>\", line 50, in <cell line: 31>\n","    random_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1960, in _run_search\n","    evaluate_candidates(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"output_type":"stream","name":"stderr","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"output_type":"stream","name":"stdout","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"<ipython-input-38-a339aeb5a6c6>\", line 50, in <cell line: 31>\n","    random_search.fit(X_train_inliers, y_train_inliers)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/base.py\", line 1473, in wrapper\n","    return fit_method(estimator, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1019, in fit\n","    self._run_search(evaluate_candidates)\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 1960, in _run_search\n","    evaluate_candidates(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py\", line 965, in evaluate_candidates\n","    out = parallel(\n","  File \"/usr/local/lib/python3.10/dist-packages/sklearn/utils/parallel.py\", line 74, in __call__\n","    return super().__call__(iterable_with_config)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 2005, in __call__\n","    next(output)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1643, in _get_outputs\n","    self._start(iterator, pre_dispatch)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1626, in _start\n","    if self.dispatch_one_batch(iterator):\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1517, in dispatch_one_batch\n","    self._dispatch(tasks)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/parallel.py\", line 1418, in _dispatch\n","    job = self._backend.apply_async(batch, callback=batch_tracker)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/_parallel_backends.py\", line 588, in apply_async\n","    future = self._workers.submit(func)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/reusable_executor.py\", line 225, in submit\n","    return super().submit(fn, *args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1248, in submit\n","    self._ensure_executor_running()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1220, in _ensure_executor_running\n","    self._adjust_process_count()\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/process_executor.py\", line 1209, in _adjust_process_count\n","    p.start()\n","  File \"/usr/lib/python3.10/multiprocessing/process.py\", line 121, in start\n","    self._popen = self._Popen(self)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/process.py\", line 45, in _Popen\n","    return Popen(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 48, in __init__\n","    self._launch(process_obj)\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py\", line 99, in _launch\n","    prep_data = spawn.get_preparation_data(\n","  File \"/usr/local/lib/python3.10/dist-packages/joblib/externals/loky/backend/spawn.py\", line 68, in get_preparation_data\n","    dir=os.getcwd(),\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}]}],"metadata":{"colab":{"provenance":[{"file_id":"1xtubTTvSW3YBrMFYjarTpwQIJ3PYLTVG","timestamp":1729444823147},{"file_id":"1vJhvTpTD3PhtaGxMW_n5Cetro-tiwIQ0","timestamp":1729313878490},{"file_id":"1vbBEsonBcBXmX52xLaImBBbGy0cpusr-","timestamp":1728013139100},{"file_id":"1M_85TxDI7JhjFXkmHyUeKBkpTccvcnt0","timestamp":1727407593051},{"file_id":"1tCNl-JcueGmNpD4OxRNyLuleUUXsMYH_","timestamp":1726220211340},{"file_id":"1bElswYxfkl4uI372RGL86wuwHZywTgJL","timestamp":1726140131893}],"toc_visible":true,"gpuType":"T4"},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.13"}},"nbformat":4,"nbformat_minor":0}